spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flightdb
    username: root
    password: root_1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

