server:
  port: 5000
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 4000
---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 7070

#  java -jar Esercizio6-0.0.6.jar --spring.profiles.active=prod

