spring:
  config:
    activate:
      on-profile: test
server:
  port: 4000
application:
  welcomeMsg: Hello from Test
---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 5000
application:
  welcomeMsg: Hello from Prod
#---
#server:
#  port: 8080